FROM python:3.13.3-slim-bookworm

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update && apt-get -y upgrade && \
    apt-get -y install \
    procps \
    libpq-dev \
    gcc && \
    apt-get clean && \
    apt-get -y purge && \
    rm -rf /var/lib/apt/lists/* \
    /tmp/* \
    /var/tmp/* \
    /var/cache/apt

RUN pip install --no-cache-dir \
numpy==2.2.5 \
pandas=2.2.3 \
labkey==2.5.1 \
intervaltree==3.1.0 \
click==8.1.3 \
fastparquet==2024.11.0 \
python-dateutil==2.8.2 \
pytz==2023.3 \
pyarrow==19.0.0 \
PyYAML \
six==1.16.0 \
tzdata==2023.3 \
psycopg2==2.9.10